// รายชื่ออุตสาหกรรมหลักในประเทศไทย (ใช้ใน CRM — เลือกจากดรอปดาวหรือพิมพ์เองก็ได้)
export const THAI_INDUSTRIES: string[] = [
  "ยานยนต์และชิ้นส่วน (Automotive)",
  "อิเล็กทรอนิกส์ / เซมิคอนดักเตอร์ / PCB",
  "เครื่องใช้ไฟฟ้า (Electrical Appliances)",
  "อาหารและเครื่องดื่ม (Food & Beverage)",
  "ยา / เวชภัณฑ์ / เครื่องมือแพทย์",
  "เครื่องสำอาง / ของใช้ส่วนตัว (FMCG)",
  "ปิโตรเคมี / เคมีภัณฑ์",
  "พลาสติก / บรรจุภัณฑ์ (Plastic & Packaging)",
  "ยางและผลิตภัณฑ์ยาง",
  "เหล็ก / โลหะการ (Steel & Metal)",
  "เครื่องจักรและอุปกรณ์ (Machinery)",
  "สิ่งทอ / เครื่องนุ่งห่ม",
  "กระดาษ / สิ่งพิมพ์",
  "แก้ว / เซรามิก / วัสดุก่อสร้าง",
  "เฟอร์นิเจอร์ / ไม้",
  "โลจิสติกส์ / คลังสินค้า / 3PL",
  "ค้าปลีก / ค้าส่ง / E-commerce",
  "เกษตรแปรรูป / อาหารสัตว์",
  "พลังงาน / โซลาร์เซลล์",
  "ก่อสร้าง / รับเหมา / นิคมอุตสาหกรรม",
  "System Integrator (SI)",
  "ตัวแทนจำหน่าย (Dealer / Distributor)",
  "อื่นๆ",
];

// ความสนใจของลูกค้า = โซลูชันที่บริษัทขาย (เลือกได้หลายอัน)
export const SOLUTION_INTERESTS: string[] = [
  "AGV, AMR (Automated Guided Vehicle / Autonomous Mobile Robot)",
  "FMS (Fleet Management System)",
  "WMS (Warehouse Management System — ระบบจัดการคลังสินค้า)",
  "MES (Manufacturing Execution System — ระบบจัดการการผลิต)",
  "OEE (Overall Equipment Effectiveness — วัดประสิทธิผลเครื่องจักร)",
  "PM (Preventive Maintenance — ระบบบำรุงรักษาเชิงป้องกัน)",
  "เชื่อมต่อระบบ ERP (Enterprise Resource Planning)",
  "ระบบสายพานลำเลียง (Conveyor System)",
  "คลังสินค้าอัตโนมัติ AS/RS (Automated Storage & Retrieval System)",
  "ปรับปรุง/ดัดแปลงเครื่องจักร (Retrofit)",
  "บริการซ่อมบำรุง MA (Maintenance Agreement)",
  "อะไหล่ (Spare Parts)",
  "สำรวจหน้างาน / ที่ปรึกษาระบบอัตโนมัติ",
];
